apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ssh://git@github.com:Chris-Carmichael/kustomize-remote.git//sre-test/sre-sha/base

commonLabels:
  owner: sre-team
  environment: dev

namespace: sre-sha

images:
  - name: ecr/sre-sha
    newName: ecr/sre-sha
    newTag: master_33c3c3c3
