apiVersion: v2
name: traefik
description: Traefik Load Balancer
type: application

version: 0.1.0
appVersion: "1.0"

dependencies:
- name: traefik
  version: 10.6.0
  repository: https://helm.traefik.io/traefik
